manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: copocaneta
      url-base: https://github.com/copocaneta
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-nice-oled
      remote: copocaneta
      revision: ebaf5818c7d0b4c2657a202aca4a565231eade1c
  self:
    path: config
